export const FILTER_EXHIBITS_FOR_MAPS = "FILTER_EXHIBITS_FOR_MAPS";
export const INPUT_SEARCH_VALUE = "INPUT_SEARCH_VALUE";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const SELECTED_EXHIBIT = "SELECTED_EXHIBIT";
